services:
  nginx:
    image: nginx:1.19-alpine
    container_name: loan_api_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: ./docker
      args:
        - YII_ENV=${YII_ENV}
    container_name: loan_api_app
    restart: always
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    environment:
      - YII_ENV=${YII_ENV}
      - PHP_MAX_EXECUTION_TIME=300
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Указываем entrypoint, отключая скрипт образа
    entrypoint: /bin/bash
    # Передаем 'command:' как аргумент для /bin/bash
    # Используем формат списка и YAML-блок '|' для чистоты
    command:
      - "-c"
      - |
        echo '>>> (1/6) Script started.';
        echo '>>> (2/6) Running composer install...';

        if [ "$$YII_ENV" = "dev" ]; then
          php -d memory_limit=-1 -d xdebug.mode=off /usr/local/bin/composer.phar install -v --no-interaction --prefer-dist --optimize-autoloader;
        else
          php -d memory_limit=-1 /usr/local/bin/composer.phar install -v --no-interaction --prefer-dist --optimize-autoloader --no-dev;
        fi;

        echo '>>> (3/6) Composer install finished.'

        echo '>>> (4/6) Setting up permissions for runtime/assets...';
        chown -R www-data:www-data /app/runtime /app/web/assets;
        echo '>>> (5/6) Permissions set.'

        echo '>>> (6/6) Running migrations...';
        php -d xdebug.mode=off /app/yii migrate --interactive=0;

        echo '>>> Migrations complete. Starting PHP-FPM...';
        exec php-fpm
        "

  db:
    image: postgres:13-alpine
    container_name: loan_api_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d loans"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: